### ISSUE TITLE
Request to add papers on Referring Video Object Segmentation

### ISSUE THREAD

**Issue by leonnnop** [MarkMoHR/Awesome-Referring-Image-Segmentation#13]
Thank you for organizing this great repository! 

I would like to request the addition of three papers on Referring Video Object Segmentation to the repository. Below is the detailed information organized in a markdown table for your convenience:

| Short name | Paper | Source | Code/Project Link  |
| --- | --- | --- | --- |
| Locater | [Local-Global Context Aware Transformer for Language-Guided Video Segmentation](https://ieeexplore.ieee.org/abstract/document/10083244) | TPAMI 2023 | [[code]](https://github.com/leonnnop/Locater) [[dataset]](https://github.com/leonnnop/Locater) |
| CITD | [Rethinking Cross-modal Interaction from a Top-down Perspective for Referring Video Object Segmentation](https://arxiv.org/abs/2106.01061) | CVPRW 2021 |  |
| ClawCraneNet | [ClawCraneNet: Leveraging Object-level Relation for Text-based Video Segmentation](https://arxiv.org/abs/2103.10702) | arXiv 21.03 |  |

Thanks in advance.

**Comment by MarkMoHR** [comment]
Done. Thank you very much!
