### ISSUE TITLE
Request to add papers on Referring Video Object Segmentation

### ISSUE THREAD

**Issue by workforai** [MarkMoHR/Awesome-Referring-Image-Segmentation#14]
Hi, thanks for organizing this helpful repository. I would like to request the addition of our paper on Referring Video Object Segmentation to the repository. The paper is "SOC: Semantic-Assisted Object Cluster for Referring Video Object Segmentation". The corresponding code is also available at https://github.com/RobertLuo1/NeurIPS2023_SOC. Thanks in advance!

**Comment by MarkMoHR** [comment]
Done. Thanks!
