### ISSUE TITLE
Sincere request to add our paper "CM-MaskSD: Cross-Modality Masked Self-Distillation for Referring Image Segmentation"

### ISSUE THREAD

**Issue by Rubics-Xuan** [MarkMoHR/Awesome-Referring-Image-Segmentation#16]
Hello,

Hope you have a great day!

Can you add our paper "CM-MaskSD: Cross-Modality Masked Self-Distillation for Referring Image Segmentation"(https://arxiv.org/abs/2305.11481), which is accepted by IEEE-TMM 2024? And can you please add the project page link (https://rubics-xuan.github.io/MRES/) for our CVPR 2024 paper "Unveiling Parts Beyond Objects:Towards Finer-Granularity Referring Expression Segmentation"?

Thanks

**Comment by MarkMoHR** [comment]
Done. Thanks!

**Comment by Rubics-Xuan** [comment]
Many thanks! Hope you have a great day!
