### ISSUE TITLE
Request to add paper

### ISSUE THREAD

**Issue by Seonghoon-Yu** [MarkMoHR/Awesome-Referring-Image-Segmentation#17]
Hi,
can you add my RIS paper, titled "A Simple Baseline with Single-encoder for Referring Image Segmentation" and called "Shared-RIS" ?
arxiv: https://arxiv.org/abs/2408.15521
code: https://github.com/Seonghoon-Yu/Shared-RIS 

Thanks

**Comment by MarkMoHR** [comment]
Done. Thanks!
