### ISSUE TITLE
Request to add new paper

### ISSUE THREAD

**Issue by itruonghai** [MarkMoHR/Awesome-Referring-Image-Segmentation#20]
Hi,

Thanks for maintaining the repository. I'd like to request the addition of our paper, "VATEX: Vision-Aware Text Features in Referring Image Segmentation: From Object Understanding to Context Understanding", which is currently accepted at **WACV 2025**

Paper Link: https://arxiv.org/abs/2404.08590
Project Page: https://vatex.hkustvgd.com/

Thanks.

**Comment by MarkMoHR** [comment]
Done. Thanks!
