### ISSUE TITLE
Encoder Fusion Network with Co-Attention Embedding for Referring Image Segmentation

### ISSUE THREAD

**Issue by fengguang94** [MarkMoHR/Awesome-Referring-Image-Segmentation#4]
Hello, can you update the code link of 'Encoder Fusion Network with Co-Attention Embedding for Referring Image Segmentation'?  Code: https://github.com/fengguang94/CEFNet

**Comment by MarkMoHR** [comment]
Done. Thanks!

**Comment by fengguang94** [comment]
Thanks !

Haoran MO ***@***.***> 于2022年5月31日周二 10:15写道：
