### ISSUE TITLE
Please add our paper "PolyFormer: Referring Image Segmentation as Sequential Polygon Generation”

### ISSUE THREAD

**Issue by joellliu** [MarkMoHR/Awesome-Referring-Image-Segmentation#5]
Hi,

Can you add our paper "PolyFormer: Referring Image Segmentation as Sequential Polygon Generation"
[https://arxiv.org/abs/2302.07387](https://arxiv.org/abs/2302.07387) to the list? It is accepted by CVPR 23. Thank you!

**Comment by MarkMoHR** [comment]
Done. Thanks!

**Comment by joellliu** [comment]
Hi @MarkMoHR, can you also add our project page? https://polyformer.github.io/
Thank you so much!

**Comment by MarkMoHR** [comment]
Done. Thank you.
