### ISSUE TITLE
Please add short name (Global-Local CLIP) for our paper "Zero-shot Referring Image Segmentation with GLobal-Local Context Features" 

### ISSUE THREAD

**Issue by Seonghoon-Yu** [MarkMoHR/Awesome-Referring-Image-Segmentation#9]
Hello,

Can you add the short name (Global-Local CLIP) for our paper "Zero-shot Referring Image Segmentation with GLobal-Local Context Features"?

Thanks

**Comment by MarkMoHR** [comment]
Done. Thanks!
